# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_service_pb2 as books__service__pb2


class BooksDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/bookstore.BooksDatabase/Read',
                request_serializer=books__service__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__service__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/bookstore.BooksDatabase/Write',
                request_serializer=books__service__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__service__pb2.WriteResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/bookstore.BooksDatabase/Update',
                request_serializer=books__service__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__service__pb2.WriteResponse.FromString,
                )
        self.Increment = channel.unary_unary(
                '/bookstore.BooksDatabase/Increment',
                request_serializer=books__service__pb2.AdjustRequest.SerializeToString,
                response_deserializer=books__service__pb2.WriteResponse.FromString,
                )
        self.Decrement = channel.unary_unary(
                '/bookstore.BooksDatabase/Decrement',
                request_serializer=books__service__pb2.AdjustRequest.SerializeToString,
                response_deserializer=books__service__pb2.WriteResponse.FromString,
                )
        self.Exists = channel.unary_unary(
                '/bookstore.BooksDatabase/Exists',
                request_serializer=books__service__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__service__pb2.ExistsResponse.FromString,
                )


class BooksDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Increment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decrement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=books__service__pb2.ReadRequest.FromString,
                    response_serializer=books__service__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=books__service__pb2.WriteRequest.FromString,
                    response_serializer=books__service__pb2.WriteResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=books__service__pb2.WriteRequest.FromString,
                    response_serializer=books__service__pb2.WriteResponse.SerializeToString,
            ),
            'Increment': grpc.unary_unary_rpc_method_handler(
                    servicer.Increment,
                    request_deserializer=books__service__pb2.AdjustRequest.FromString,
                    response_serializer=books__service__pb2.WriteResponse.SerializeToString,
            ),
            'Decrement': grpc.unary_unary_rpc_method_handler(
                    servicer.Decrement,
                    request_deserializer=books__service__pb2.AdjustRequest.FromString,
                    response_serializer=books__service__pb2.WriteResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=books__service__pb2.ReadRequest.FromString,
                    response_serializer=books__service__pb2.ExistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.BooksDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Read',
            books__service__pb2.ReadRequest.SerializeToString,
            books__service__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Write',
            books__service__pb2.WriteRequest.SerializeToString,
            books__service__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Update',
            books__service__pb2.WriteRequest.SerializeToString,
            books__service__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Increment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Increment',
            books__service__pb2.AdjustRequest.SerializeToString,
            books__service__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decrement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Decrement',
            books__service__pb2.AdjustRequest.SerializeToString,
            books__service__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookstore.BooksDatabase/Exists',
            books__service__pb2.ReadRequest.SerializeToString,
            books__service__pb2.ExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
