# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import userdata_pb2 as userdata__pb2
import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\tbookstore\x1a\x0euserdata.proto\x1a\x0border.proto\"{\n\x16InitDetectFraudRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12%\n\x08userData\x18\x02 \x01(\x0b\x32\x13.bookstore.UserData\x12)\n\ncreditCard\x18\x03 \x01(\x0b\x32\x15.bookstore.CreditCard2\xf2\x01\n\x15\x46raudDetectionService\x12M\n\x0fInitDetectFraud\x12!.bookstore.InitDetectFraudRequest\x1a\x17.bookstore.InitResponse\x12\x41\n\x0f\x44\x65tectUserFraud\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponse\x12G\n\x15\x44\x65tectCreditCardFraud\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITDETECTFRAUDREQUEST']._serialized_start=65
  _globals['_INITDETECTFRAUDREQUEST']._serialized_end=188
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=191
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
