# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import userdata_pb2 as userdata__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\tbookstore\x1a\x0euserdata.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n\x15PreparePaymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x08userData\x18\x02 \x01(\x0b\x32\x13.bookstore.UserData\x12)\n\ncreditCard\x18\x03 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\r\n\x05price\x18\x04 \x01(\x02\"\'\n\x16PreparePaymentResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"3\n\x16\x46inalizePaymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61\x62ort\x18\x02 \x01(\x08\x32\xb5\x01\n\x0ePaymentService\x12U\n\x0ePreparePayment\x12 .bookstore.PreparePaymentRequest\x1a!.bookstore.PreparePaymentResponse\x12L\n\x0f\x46inalizePayment\x12!.bookstore.FinalizePaymentRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREPAYMENTREQUEST']._serialized_start=74
  _globals['_PREPAREPAYMENTREQUEST']._serialized_end=206
  _globals['_PREPAREPAYMENTRESPONSE']._serialized_start=208
  _globals['_PREPAREPAYMENTRESPONSE']._serialized_end=247
  _globals['_FINALIZEPAYMENTREQUEST']._serialized_start=249
  _globals['_FINALIZEPAYMENTREQUEST']._serialized_end=300
  _globals['_PAYMENTSERVICE']._serialized_start=303
  _globals['_PAYMENTSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
