# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\tbookstore\x1a\x0border.proto\">\n\x17InitSuggestBooksRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x12\n\nbookTitles\x18\x02 \x03(\t2\xa4\x01\n\x11SuggestionService\x12O\n\x10InitSuggestBooks\x12\".bookstore.InitSuggestBooksRequest\x1a\x17.bookstore.InitResponse\x12>\n\x0cSuggestBooks\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITSUGGESTBOOKSREQUEST']._serialized_start=45
  _globals['_INITSUGGESTBOOKSREQUEST']._serialized_end=107
  _globals['_SUGGESTIONSERVICE']._serialized_start=110
  _globals['_SUGGESTIONSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
