# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import order_pb2 as order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\tbookstore\x1a\x0border.proto2\xe2\x02\n\x12TransactionService\x12\x46\n\x15InitVerifyTransaction\x12\x14.bookstore.OrderData\x1a\x17.bookstore.EmptyMessage\x12=\n\x0bVerifyItems\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponse\x12@\n\x0eVerifyUserData\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponse\x12\x42\n\x10VerifyCreditCard\x12\x14.bookstore.OrderInfo\x1a\x18.bookstore.OrderResponse\x12?\n\tClearData\x12\x14.bookstore.OrderInfo\x1a\x1c.bookstore.ClearDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONSERVICE']._serialized_start=59
  _globals['_TRANSACTIONSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
